# Generated by Django 3.2.25 on 2026-01-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(blank=True, max_length=250, null=True)),
                ('comuna', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.IntegerField(default=0)),
                ('long', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CVUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.BinaryField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra4', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra5', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra6', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra7', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra8', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra9', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra10', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_qr', models.BinaryField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar del Evento')),
                ('costo', models.IntegerField(default=0, verbose_name='Costo Estimado')),
            ],
            options={
                'verbose_name': 'Evento Académico',
                'verbose_name_plural': 'Eventos Académicos',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id_idea', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SIN_ENVIAR', 'No Notificado'), ('ENVIADO', 'Esperando Confirmación'), ('CONFIRMADO', 'Asistencia Confirmada'), ('RECHAZADO', 'No Asistirá'), ('ENTRADA_ENVIADA', 'Invitación Formal Enviada')], default='SIN_ENVIAR', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id_necesidad', models.AutoField(primary_key=True, serialize=False)),
                ('texto_necesita', models.TextField()),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_oferta', models.TextField()),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidades',
            fields=[
                ('id_oportunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_universidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=150)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrera')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etapa')),
            ],
        ),
    ]
