# Generated by Django 3.2.25 on 2026-01-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.carrera', verbose_name='Carrera Organizadora'),
            preserve_default=False,
        ),
    ]
