# Generated by Django 3.2.25 on 2026-01-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20260120_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_departamento', to='app.departamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_facultad', to='app.facultad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.carrera', verbose_name='Carrera Organizadora'),
        ),
    ]
