# Generated by Django 3.2.25 on 2026-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20260120_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='recordatorio_24h_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio Auto Enviado'),
        ),
    ]
