# Generated by Django 3.2.25 on 2026-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_evento_recordatorio_24h_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='palabra4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='palabra5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='palabra4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='palabra5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
