# Generated by Django 5.2.11 on 2026-02-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20260128_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('expositor', 'Pregunta al Expositor'), ('publico', 'Respuesta al Público')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('score_ia', models.FloatField(default=0.0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='app.evento')),
            ],
        ),
    ]
