# Generated by Django 5.2.11 on 2026-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_preguntaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contador_aportes',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Respuestas del Público'),
        ),
        migrations.AddField(
            model_name='evento',
            name='contador_preguntas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Preguntas al Expositor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pregunta_del_coordinador',
            field=models.CharField(blank=True, default='¿Qué opinas de este tema?', max_length=255, null=True, verbose_name='Pregunta Dinámica del Coordinador'),
        ),
    ]
