# Generated by Django 5.2.11 on 2026-02-18 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_evento_contador_aportes_evento_contador_preguntas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(choices=[('SIN_ENVIAR', 'No Notificado'), ('ENVIADO', 'Esperando Confirmación'), ('CONFIRMADO', 'Asistencia Confirmada'), ('PAGADO', 'Entrada Pagada'), ('RECHAZADO', 'No Asistirá'), ('ENTRADA_ENVIADA', 'Invitación Formal Enviada')], default='SIN_ENVIAR', max_length=20),
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id_transaccion', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID de Transacción MP')),
                ('monto', models.IntegerField(verbose_name='Monto Pagado')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=50, verbose_name='Estado del Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
            },
        ),
    ]
