# Generated by Django 5.2.11 on 2026-03-05 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invitacion_estado_transaccionpago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='correos_adjuntos/')),
                ('filtros_aplicados', models.CharField(max_length=255)),
                ('cantidad_destinatarios', models.IntegerField(default=0)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
