# Generated by Django 6.0.3 on 2026-03-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_logcorreo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='texto_oferta',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='oferta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.carrera'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='empresa',
            field=models.CharField(default='sin empresa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='jornada',
            field=models.CharField(choices=[('completa', 'Jornada Completa'), ('parcial', 'Jornada Parcial'), ('practica', 'Práctica')], default='completa', max_length=20),
        ),
        migrations.AddField(
            model_name='oferta',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='oferta',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='salario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.universidad'),
        ),
    ]
