# Generated by Django 5.2.7 on 2026-04-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_documentobiblioteca_subido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=300)),
                ('problema', models.TextField()),
                ('solucion', models.TextField()),
                ('llamada_accion', models.CharField(max_length=300)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
