# Generated by Django 5.2.11 on 2026-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20260127_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
    ]
