# Generated by Django 5.2.11 on 2026-02-24 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usuario_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Socio', 'Socio / Dueño'), ('Trabajo', 'Empleado / Colaborador')], max_length=20, verbose_name='Relación')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL / Sitio Web')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('descripcion_breve', models.TextField(max_length=500, verbose_name='Descripción breve')),
                ('categoria_ia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría (Generada por IA)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
