# Generated by Django 5.2.11 on 2026-02-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_trabajoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pregunta', models.CharField(max_length=200)),
                ('icono', models.CharField(default='fa-tag', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='user.preferencia'),
        ),
    ]
