# Generated by Django 5.2.11 on 2026-02-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invitacion_estado_transaccionpago'),
        ('user', '0006_preferencia_usuario_preferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='app.universidad'),
        ),
    ]
