# Generated by Django 5.2.11 on 2026-02-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invitacion_estado_transaccionpago'),
        ('user', '0007_preferencia_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(default='fa-building-columns', max_length=50)),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='app.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='descuentos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_banco', to='user.descuentobanco'),
        ),
    ]
