# Generated by Django 5.2.11 on 2026-03-02 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invitacion_estado_transaccionpago'),
        ('user', '0008_descuentobanco_usuario_descuentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anual', models.IntegerField(default=0)),
                ('descripcion', models.TextField(default='Acceso completo a la red de ex alumnos.')),
                ('universidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_membresia', to='app.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
