# Generated by Django 5.2.7 on 2026-03-26 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_producto_ordencompra'),
        ('user', '0009_planmembresia_suscripcionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.universidad', verbose_name='Universidad del Estudiante'),
        ),
    ]
